main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/urls.py
from django.urls import path

from .views import TagListView
from todo.views import (
    index,
    TaskCreateView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskUpdateView,
    TaskDeleteView,
    TaskUpdateStatusView,
)


urlpatterns = [
    path("", index, name="index"),

    path("tasks/create/",
         TaskCreateView.as_view(),
         name="task-create"),

    path("<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update"),

    path("<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),

    path("<int:pk>/update/status/",
         TaskUpdateStatusView.as_view(),
         name="complete-or-undo-task"),

    path("tags/",
         TagListView.as_view(),
         name="tag-list"),

    path("tags/create/",
         TagCreateView.as_view(),
         name="tag-create"),

    path("tags/<int:pk>/update/",
         TagUpdateView.as_view(),
         name="tag-update"),

    path("tags/<int:pk>/delete/",
         TagDeleteView.as_view(),
         name="tag-delete"),

]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    done_mark = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["done_mark", "-date"]

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from django.forms import DateTimeInput

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "deadline": DateTimeInput(
                attrs={"type": "datetime-local"}, format="%Y-%m-%dT%H:%M"
            )
        }

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from todo.forms import TaskForm
from todo.models import Task, Tag


def index(request):
    tasks = Task.objects.all()
    tags = Tag.objects.all()

    context = {
        "tasks": tasks,
        "tags_list": tags,
    }

    return render(request, "todo/index.html", context=context)


class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("todo:index")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskUpdateStatusView(View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.done_mark = not task.done_mark
        task.save()
        return HttpResponseRedirect(reverse_lazy("todo:index"))


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    fields = "__all__"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% block title %}<title>do-to-do service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-2">
          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>

        <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">All Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}
{% block content %}
  <h1>
    DO TO DO list
    <a class="btn btn-primary link-to-page" href="{% url 'todo:task-create' %}">
      Add task
    </a>
  </h1>
  <hr>
  {% if tasks %}
    {% for task in tasks %}
      <p><strong>{{task.name}}{% if task.done_mark %} <span class="text-success">Done</span>{% else %} <span class="text-danger">Not done</span>{% endif %}</strong></p>
          {% if task.done_mark is True %}
            <a href="{% url 'todo:complete-or-undo-task' pk=task.id%}" class="btn btn-dark link-to-page">Undo</a>
          {% else %}
            <a href="{% url 'todo:complete-or-undo-task' pk=task.id%}" class="btn btn-success link-to-page">Complete</a>
          {% endif %}

      <p><small>Created: {{ task.date|date:"F j, Y, H:i" }} {% if task.deadline %} <span class="text-danger"> Deadline: {{ task.deadline|date:"F j, Y, H:i" }}{% endif %}</span></small></p>
      <p>
        Tags:
        {% for tag in task.tags.all %}
          #{{ tag.name }}
        {% endfor %}
         <a href="{% url 'todo:task-update' pk=task.id %}">Update</a> <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
      </p>
      <hr>
    {% endfor %}
  {% else %}
      <p>There are no tasks yet! </p>
  {% endif %}
{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete << {{ tag }} >> Tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <hr>
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a class="btn btn-primary link-to-page" href="{% url 'todo:tag-create' %}">Add</a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
            <a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags yet!</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete << {{ task }} >> Task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <hr>
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary">
    <a href="javascript:history.back()" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}